services:
  mysql:
    image: mysql:8.0
    container_name: techchallenge3-mysql
    environment:
      MYSQL_DATABASE: techchallenge3
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "fiap", "-pfiap123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - fase3net

  app:
    build: .
    container_name: techchallenge3-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/techchallenge3?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: fiap
      DB_PASSWORD: fiap123
      DDL_AUTO: update
      JPA_SHOW_SQL: "false"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fase3net

  procpag:
    image: docker.io/erickemprobr/procpag:latest
    platform: linux/amd64
    ports:
      - "8089:8089"
    networks:
      - fase3net

volumes:
  mysql_data:

networks:
  fase3net: