services:
  mysql:
    image: mysql:8.0
    container_name: techchallenge3-mysql
    environment:
      MYSQL_DATABASE: techchallenge3
      MYSQL_USER: fiap
      MYSQL_PASSWORD: fiap123
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "fiap", "-pfiap123"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - fase3net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: techchallenge3-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - fase3net

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: techchallenge3-kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - fase3net

  app:
    build: .
    container_name: techchallenge3-app
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://mysql:3306/techchallenge3?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USERNAME: fiap
      DB_PASSWORD: fiap123
      DDL_AUTO: update
      JPA_SHOW_SQL: "false"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      JWT_SECRET: chave-secreta-minimo-256-bits-para-hmac-sha256-fiap
      JWT_EXPIRATION: 86400000
    depends_on:
      mysql:
        condition: service_healthy
      kafka:
        condition: service_started
    networks:
      - fase3net

  procpag:
    image: docker.io/erickemprobr/procpag:latest
    platform: linux/amd64
    ports:
      - "8089:8089"
    networks:
      - fase3net

volumes:
  mysql_data:

networks:
  fase3net: