spring.application.name=tech-challenge2

# DataSource
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/techchallenge3?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:fiap}
spring.datasource.password=${DB_PASSWORD:fiap123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=${DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# SQL Init
spring.sql.init.mode=always

# Actuator
management.endpoints.web.exposure.include=health,info

# Springdoc / Swagger
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=chave-secreta-minimo-256-bits-para-hmac-sha256-fiap
jwt.expiration=86400000

